#rMATS result file, AS type, P-value cutoff, DPSI cutoff
#SUPPA result file, gtf file, ioe file, gene model, P-value cutoff, DPSI cutoff
#spliceR result file, gene model, genome version, pvalue cutoff

#' Generate ASpedia-R input format from DAS analysis tools result.
#'
#' @param input.file.name
#' name of DAS analysis tools result file.
#' @param program
#' name of DAS analysis tool. (one of rMATS, SUPPA, and spliceR)
#' @param pvalue.cutoff
#' value of pvalue cutoff. default value is 0.05
#' @param das.cutoff
#' value of dPSI cutoff. default value is 0.1
#' @param gene.model
#' gene model of reference (SUPPA and spliceR).
#' @param genome.version
#' genome version of reference. (SUPPA and spliceR).
#' @param as.type
#' AS event type. One of A3SS, A5SS, SE, MXE, and RI. (rMATS only)
#' @param gtf.file.name
#' a GTF format file of reference. (SUPPA only)
#' @param ioe.file.name
#' name of ioe file generated by SUPPA generateEvents command.
#'
#' @return converter.result
#' @export
#'
#' @examples 
#' das.file.name <- “examples/rMATS_test.txt”
#' rmats.converter.result <- asr_converter(das.file.name, program=”rMATS”, as.type=”SE”)

asr_converter <- function(input.file.name="", program="", pvalue.cutoff=0.05, das.cutoff=0.1, gene.model="Ensembl", genome.version="hg38", as.type="", gtf.file.name="", ioe.file.name="") {
  if(tolower(program) == "rmats") {
    #source("R/rMATS_converter.R")
    converter.result <- rMATS.converter(input.file.name, as.type, pvalue.cutoff, das.cutoff)

    return(converter.result)
  } else if(tolower(program) == "suppa") {
    #source("R/SUPPA_converter.R")
    converter.result <- SUPPA.converter(input.file.name, gtf.file.name, ioe.file.name, pvalue.cutoff, das.cutoff)

    return(converter.result)
  } else if(tolower(program) == "splicer") {
    #source("R/spliceR_converter.R")
    converter.result <- spliceR.converter(input.file.name, gene.model, genome.version, pvalue.cutoff)

    return(converter.result)
  } else {
    print("ERROR : Input program name is wrong. Please check program option. We currently support rMATS, SUPPA, or spliceR.")
    return()
  }
}
